apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: voting-app
  namespace: argocd
spec:
  description: A project for the kind-voting-app

  sourceRepos:
    - 'https://github.com/Shouryabisht24/kind-voting-app'
  
  destinations:
    - namespace: voting-app
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:    # Which cluster-wide resources are allowed (e.g., CRDs)
    - group: "*"               # '*' means allow all groups
      kind: "*"                # '*' means allow all kinds
  namespaceResourceWhitelist:  # Which namespace-level resources are allowed
    - group: "*"               # Here also allowing everything
      kind: "*"
  roles:                       # Define roles for RBAC within this Project
    - name: frontend-admins    # Role name  
      description: Admins for frontend team
      policies:                # Policies associated with this role
        # syntax: - p, proj:<project-name>:<role-name>, applications, <action>, <project>/<app-name>, permission(allow|deny)
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow